# Generated by Django 2.2.6 on 2021-05-11 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('file', models.FileField(upload_to='illust/file', verbose_name='ファイル')),
            ],
            options={
                'db_table': 'design',
            },
        ),
    ]
